// Generated by CoffeeScript 1.9.3
(function() {
  var passwordHash;

  passwordHash = require('password-hash');

  module.exports = function(db) {
    var User;
    User = db.models.user;
    return User.create({
      username: 'test',
      password: passwordHash.generate('test'),
      privilege: 'admin'
    }).then(function() {
      return console.log('ok');
    });
  };

}).call(this);

//# sourceMappingURL=init.js.map
