// Generated by CoffeeScript 1.9.3
(function() {
  var passwordHash, promise;

  passwordHash = require('password-hash');

  promise = require('sequelize').Promise;

  module.exports = function(db) {
    var Tag, User;
    User = db.models.user;
    Tag = db.models.tag;
    return User.create({
      username: 'test',
      password: passwordHash.generate('test'),
      privilege: 'admin'
    }).then(function() {
      return User.create({
        username: 'admin',
        password: passwordHash.generate('21232f297a57a5a743894a0e4a801fc3'),
        privilege: 'admin'
      });
    }).then(function() {
      return Tag.create({
        content: "待分发"
      });
    }).then(function() {
      return Tag.create({
        content: "待回复"
      });
    }).then(function() {
      return Tag.create({
        content: "待审核"
      });
    }).then(function() {
      return Tag.create({
        content: "待发送"
      });
    }).then(function() {
      return Tag.create({
        content: "已回复"
      });
    }).then(function() {
      return console.log('ok');
    });
  };

}).call(this);

//# sourceMappingURL=init.js.map
