// Generated by CoffeeScript 1.9.3
(function() {
  exports.getDetail = function(req, res) {
    var User;
    User = global.db.models.user;
    return global.db.Promise.resolve().then(function() {
      if (req.session.user) {
        return User.findById(req.session.user.id);
      }
    }).then(function(user) {
      var config;
      if (!user) {
        throw new global.myError.UnknownUser();
      }
      if (user.privilege !== 'admin') {
        throw new global.myError.InvalidAccess();
      }
      config = global.myConfig.mail;
      return res.json({
        status: 1,
        msg: "Success",
        config: config
      });
    })["catch"](function(err) {
      return res.json({
        status: 0,
        msg: err.message
      });
    });
  };

  exports.postEdit = function(req, res) {
    var User;
    User = global.db.models.user;
    return global.db.Promise.resolve().then(function() {
      if (req.session.user) {
        return User.findById(req.session.user.id);
      }
    }).then(function(user) {
      var config, transporter;
      if (!user) {
        throw new global.myError.UnknownUser();
      }
      if (user.privilege !== 'admin') {
        throw new global.myError.InvalidAccess();
      }
      config = global.myConfig.mail;
      if (req.body.host) {
        config.host = req.body.host;
      }
      if (req.body.port) {
        config.port = req.body.port;
      }
      if (req.body.auth) {
        config.auth = req.body.auth;
      }
      transporter = mailer.createTransport({
        host: config.smtp.host,
        port: config.smtp.port,
        secure: true,
        auth: {
          user: config.auth.mailaddr,
          pass: config.auth.password
        }
      });
      global.transporter = Promise.promisifyAll(transporter, {
        suffix: 'Promised'
      });
      return res.json({
        status: 1,
        msg: "Success",
        config: config
      });
    })["catch"](function(err) {
      return res.json({
        status: 0,
        msg: err.message
      });
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
