// Generated by CoffeeScript 1.9.3
(function() {
  var HOME_PAGE, passwordHash;

  HOME_PAGE = '/';

  passwordHash = require('password-hash');

  exports.postLogin = function(req, res) {
    var User, form;
    form = {
      username: req.body.username,
      password: req.body.password
    };
    User = global.db.models.user;
    return User.find({
      where: {
        username: form.username
      }
    }).then(function(user) {
      if (!user) {
        throw new global.Error.LoginError();
      }
      if (!passwordHash.verify(form.password, user.password)) {
        throw new global.Error.LoginError();
      }
      return res.json({
        status: 1,
        msg: "Success"
      });
    })["catch"](myUtils.Error.LoginError, function(err) {
      return res.json({
        status: 0,
        msg: err.message
      });
    })["catch"](function(err) {
      console.log(err);
      return res.redirect(HOME_PAGE);
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
