// Generated by CoffeeScript 1.9.3
(function() {
  var HOME_PAGE, Promise, sequelize;

  HOME_PAGE = '/';

  sequelize = require('sequelize');

  Promise = require('sequelize').Promise;

  exports.postSend = function(req, res) {
    var User;
    User = global.db.models.user;
    return Promise.resolve().then(function() {
      if (req.session.user) {
        return User.findById(req.session.user.id);
      }
    }).then(function(user) {
      var Util;
      if (!user) {
        throw new global.myError.UnknownUser();
      }
      Util = global.myUtil;
      if (typeof req.body.receivers === 'string') {
        req.body.receivers = JSON.parse(req.body.receivers);
      }
      return Util.message.send({
        title: req.body.title,
        html: req.body.html,
        text: req.body.text,
        sender: user.id,
        receivers: req.body.receivers
      });
    }).then(function(result) {
      console.log(result);
      return res.json({
        status: 1,
        msg: "Success"
      });
    })["catch"](global.myError.UnknownUser, sequelize.ValidationError, function(err) {
      return res.json({
        status: 0,
        msg: err.message
      });
    })["catch"](function(err) {
      console.log(err);
      return res.redirect(HOME_PAGE);
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
