// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('assignment', {});
  };

}).call(this);

//# sourceMappingURL=assignment.js.map
