// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('inbox', {
      title: {
        type: DataTypes.TEXT,
        allowNull: false
      },
      text: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      html: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      deadline: {
        type: DataTypes.DATE
      },
      accessoryPath: {
        type: DataTypes.TEXT
      },
      from: {
        type: DataTypes.TEXT
      },
      consumerId: {
        type: DataTypes.INTEGER
      },
      dispatcherId: {
        type: DataTypes.INTEGER
      },
      target: {
        type: DataTypes.INTEGER
      },
      status: {
        type: DataTypes.ENUM("received", "assigned", "handled", "finished"),
        defaultValue: "received",
        allowNull: false
      }
    });
  };

}).call(this);

//# sourceMappingURL=inbox.js.map
