// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('mailTag', {
      inboxId: {
        type: DataTypes.INTEGER,
        unique: "mail-tag"
      },
      tagId: {
        type: DataTypes.INTEGER,
        unique: "mail-tag"
      }
    });
  };

}).call(this);

//# sourceMappingURL=mail-tag.js.map
