// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('mailTag', {});
  };

}).call(this);

//# sourceMappingURL=mail-tag.js.map
