// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('outbox', {
      title: {
        type: DataTypes.TEXT,
        allowNull: false
      },
      text: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      html: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      tags: {
        type: DataTypes.TEXT
      },
      deadline: {
        type: DataTypes.DATE
      },
      accessoryPath: {
        type: DataTypes.TEXT
      },
      to: {
        type: DataTypes.TEXT
      },
      reason: {
        type: DataTypes.TEXT('long')
      },
      status: {
        type: DataTypes.ENUM("handled", "audited", "finished", "failed", "rejected"),
        defaultValue: "handled",
        allowNull: false
      }
    });
  };

}).call(this);

//# sourceMappingURL=outbox.js.map
