// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('template', {
      name: {
        type: DataTypes.STRING,
        unique: true
      },
      text: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        validate: {
          notEmpty: true
        }
      },
      html: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        validate: {
          notEmpty: true
        }
      }
    });
  };

}).call(this);

//# sourceMappingURL=template.js.map
