// Generated by CoffeeScript 1.9.3
(function() {
  var TAG_ASSIGNED, TAG_AUDITED, TAG_FINISHED, TAG_HANDLED, TAG_RECEIVED;

  TAG_RECEIVED = 1;

  TAG_ASSIGNED = 2;

  TAG_HANDLED = 3;

  TAG_AUDITED = 4;

  TAG_FINISHED = 5;

  module.exports = function(title, from, text, html) {
    var Inbox;
    Inbox = global.db.models.inbox;
    return Inbox.create({
      title: title,
      from: from,
      text: text,
      html: html,
      status: 'received'
    }).then(function(mail) {
      return mail.setTags([TAG_RECEIVED]);
    })["catch"](function(err) {
      return console.log(err);
    });
  };

}).call(this);

//# sourceMappingURL=dbhelper.js.map
