// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, isStopped, mailer, promiseWhile, work;

  Promise = require('sequelize').Promise;

  mailer = require('nodemailer');

  isStopped = false;

  promiseWhile = function(action, mailSender) {
    var my_loop, resolver;
    resolver = Promise.defer();
    my_loop = function() {
      if (isStopped) {
        return resolver.resolve();
      }
      return Promise.cast(action(mailSender)).then(my_loop)["catch"](resolver.reject);
    };
    process.nextTick(my_loop);
    return resolver.promise;
  };

  work = function(mailSender) {
    var currentMail;
    currentMail = void 0;
    return global.db.models.outbox.find({
      where: {
        status: 'audited'
      }
    }).then(function(mail) {
      if (!mail) {
        throw new global.myError.NoTask();
      }
      currentMail = mail;
      console.log({
        to: mail.to,
        subject: mail.title,
        html: mail.html
      });
      return mailSender.sendMailPromised({
        to: mail.to,
        subject: mail.title,
        html: mail.html
      });
    }).then(function() {
      currentMail.status = 'finished';
      return currentMail.save();
    })["catch"](global.myError.NoTask, function(err) {
      console.log("waiting");
      return Promise.delay(2000);
    })["catch"](function(err) {
      return console.log(err);
    });
  };

  module.exports = function(config) {
    var transporter;
    transporter = mailer.createTransport({
      host: config.smtp.host,
      port: config.smtp.port,
      secure: true,
      auth: {
        user: config.auth.mailaddr,
        pass: config.auth.password
      }
    });
    return promiseWhile(work, transporter);
  };

}).call(this);

//# sourceMappingURL=sendmaild.js.map
